# Generated by Django 3.1 on 2021-05-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_s',
            field=models.BooleanField(default=False),
        ),
    ]
